config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root to: "pages#home"
  get '/search', to: "pages#search"

  get 'pigeons/my_pigeons', to: 'pigeons#my_pigeons', as: :my_pigeons

  get "bookings/booking_rent_from", to: 'bookings#rent_from', as: :rent_from
  get "bookings/booking_rent_to", to: 'bookings#rent_to', as: :rent_to
  patch 'bookings/:id', to: 'bookings#approve', as: :approve

  resources :pigeons do
    resources :bookings, only: [ :new, :create ]

    resources :comments, only: :create
  end

  resources :bookings, only: [ :index, :show, :destroy, :update]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :pigeon
  belongs_to :user
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :pigeon

  validates :content, presence: true
end

app/models/pigeon.rb
class Pigeon < ApplicationRecord
  belongs_to :user
  has_many :bookings, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_one_attached :photo

  geocoded_by :address

  validates :name, :color, :price, :address, presence: true

  after_validation :geocode, if: :will_save_change_to_address?
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_many :bookings
  has_many :pigeons, dependent: :destroy

  devise :database_authenticatable, :registerable,
          :recoverable, :rememberable, :validatable
  validates :first_name, :last_name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!

  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name, :phone_number])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name, :phone_number])
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  def index
    @bookings = Booking.all
  end

  def show
    @booking = Booking.find(params[:id])
    @pigeon = Pigeon.find(@booking.pigeon_id)
    @seller = User.find(@pigeon.user_id)
    @buyer = User.find(@booking.user_id)
  end

  def new
    @booking = Booking.new
    @pigeon = Pigeon.find(params[:pigeon_id])
  end

  def create
    start = params[:booking]['start_date']
    end_d = params[:booking]['end_date']
    location = params[:booking][:location]
    pigeon = params[:pigeon_id]
    @booking = Booking.new(start_date: start, end_date: end_d , location: location, user_id: current_user.id, pigeon_id: pigeon )
    @booking.save
    redirect_to :rent_from
  end

  def destroy
    @booking = Booking.find(params[:id])
    @booking.delete
    redirect_to rent_to_path
  end

  def rent_from
    @bookings = Booking.all
  end

  def rent_to
    @bookings = Booking.all
  end

  def approve
    @booking = Booking.find(params[:id])
    @approved = params[:approved].to_i
    if @approved == 1
      @booking.approved = true
    else
      @booking.approved = false
    end
    @booking.save
    redirect_to rent_to_path
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def create
    @comment = Comment.new(comment_params)
    @pigeon = Pigeon.find(params[:pigeon_id])
    @comment.pigeon = @pigeon
    @comment.save
    redirect_to pigeon_path(@pigeon)
  end

  private

  def comment_params
    params.require(:comment).permit(:content)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:home, :search]

  def home
    @pigeons = Pigeon.all
  end

  def search
    @pigeons = Pigeon.near(params[:search][:query], 10)
    @count = 0
    @pigeons.each do
      @count += 1
    end

    @markers = @pigeons.geocoded.map do |pigeon|
      {
        lat: pigeon.latitude,
        lng: pigeon.longitude
      }
    end
  end
end

app/controllers/pigeons_controller.rb
class PigeonsController < ApplicationController
  skip_before_action :authenticate_user!, only: %i[index show]

  def index
    @pigeons = Pigeon.all
  end

  def show
    @pigeon = Pigeon.find(params[:id])
    @booking = Booking.new
    @marker = [{ lat: @pigeon.latitude, lng: @pigeon.longitude }]
    @owner = User.find(@pigeon.user_id)
    @comment = Comment.new
  end

  def my_pigeons
    @my_pigeons = Pigeon.where(user: current_user)
  end

  def new
    @pigeon = Pigeon.new
  end

  def create
    @pigeon = Pigeon.new(params_pigeon)
    @user = current_user
    @pigeon.user = @user
    if @pigeon.save
      redirect_to pigeon_path(@pigeon)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @pigeon = Pigeon.find(params[:id])
  end

  def update
    @pigeon = Pigeon.find(params[:id])
    if @pigeon.update(params_pigeon)
      redirect_to pigeon_path(@pigeon)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @pigeon = Pigeon.find(params[:id])
    @pigeon.destroy
    redirect_to pigeons_path
  end

  private

  def params_pigeon
    params.require(:pigeon).permit(:name, :description, :color, :price, :age, :address, :photo)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/_booking_card.html.erb
<a href= <%= bookings_path %>>
  <div class="card-trip">
  <img src="https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/greece.jpg" />
    <div class="card-trip-infos">
      <div>
        <h2> <%= booking.user_id %></h2>
      </div>
      <div>
        <h2> <%= booking.pigeon_id %></h2>
      </div>
      <div>
        <h2 class="card-trip-pricing"><%= booking.quantity %></h2>
        <p><%= booking.date %></p>
      </div>
        <img src="https://kitt.lewagon.com/placeholder/users/krokrob" class="card-trip-user avatar-bordered" />
      </div>

  </div>
</a>

app/views/bookings/_booking_card_buyer.html.erb
<a href= <%= booking_path(booking) %>>

  <div class="card-trip">
  <%# <img src="https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/greece.jpg" /> %>
    <div class="card-trip-infos">

      <div class="d-flex">

        <div>
            <h2> Seller: <%= seller.first_name %></h2>
            <h2> Buyer: <%= current_user.first_name  %></h2>
            <h2> Pigeon: <%= pigeon.name  %></h2>
          <div>
            <p>Start date: <%= booking.start_date %></p>
            <p>End date: <%= booking.end_date %></p>
          </div>
        </div>

        <div class="p-3">
          <% if booking.pigeon.photo.attached? %>
            <%= cl_image_tag booking.pigeon.photo.key, height: 300, width: 400, crop: :fill, class: "card-trip-user avatar-bordered" %>
          <% end %>
        </div>

      </div>

    </div>
  </div>

</a>

app/views/bookings/_booking_card_seller.html.erb
  <div class="card-trip" data-move-booking-target="link">
    <div class="card-trip-infos">

      <div class="d-flex">

        <div>
          <a href=<%= booking_path(booking) %>>
            <h2> Owner: <%= current_user.first_name %></h2>
            <h2> Rentee: <%= buyer.first_name %></h2>
            <h2> Pigeon: <%= pigeon.name %></h2>
            <%= booking.approved %>
            <div>
              <p>Start date: <%= booking.start_date %></p>
              <p>End date:<%= booking.end_date %></p>
            </div>
          </a>
          <div class="my-3 d-flex gap-3">
            <%# Accept --> move the card to the other column %>
            <%= button_to "Accept", approve_path(booking), method: "patch", class: "btn btn-flat", params: { approved: 1 } %>
            <%# Delete it from db %>
            <%= button_to "Reject", approve_path(booking), method: "patch", class: "btn btn-flat", params: { approved: 0 } %>

              <%# <%= link_to "Reject",
                      booking_path(booking),
                      data: { turbo_method: :delete, turbo_confirm: 'Sure?' },
                      class: "btn-flat" %>
          </div>
        </div>

          <div class="p-3">
            <% if booking.pigeon.photo.attached? %>
              <%= cl_image_tag booking.pigeon.photo.key, height: 300, width: 400, crop: :fill, class: "card-trip-user avatar-bordered" %>
            <% end %>
          </div>

      </div>

    </div>
  </div>

app/views/bookings/_form.html.erb
  <%= simple_form_for([@pigeon, @booking]) do |f| %>
  <%= f.input :start_date, as: :date, html5: true %>
  <%= f.input :end_date, as: :date, html5: true %>
  <div class='btn-flat'><%= f.button :submit %></div>
  <% end %>

app/views/bookings/index.html.erb
<h1 id="booking"><strong>Booking<strong></h1>

<div class= "container">
  <div class="card-booking">

    <button type="button" class="card-trip-booking"
        onclick="location.href='bookings/booking_rent_to'"
        style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(https://images.unsplash.com/photo-1589512842653-c7ccbec46027?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1674&q=80)">
      <div class="card-trip-infos-booking">
        <div>
          <h1><strong><%= link_to "Rent To Others", rent_to_path, class: "text-white"%></strong></h1>
        </div>
      </div>
    </button>


    <button class="card-trip-booking"
    onclick="location.href='bookings/booking_rent_from'"
        style=" background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(https://images.unsplash.com/photo-1645536737886-35e54e2ced04?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=774&q=80)">
        <div class="card-trip-infos-booking">
          <div>
            <h1><strong><%= link_to "Rent From Others", rent_from_path, class: "text-white"%></strong></h1>
          </div>
    </button>

    </div>
</div>

app/views/bookings/new.html.erb
<h1>Book your Pigeon!!!</h1>

<%= render 'form' %>

app/views/bookings/rent_from.html.erb
<br>
<br>
<div class="container">
  <h1>All the pigeons I've Booked</h1>
    <% if @bookings.empty? %>
    <% end %>
    <div class="cards">
        <% @bookings.each do |booking| %>
          <% @pigeon = Pigeon.find(booking.pigeon_id) %>
          <% @buyer = User.find(booking.user_id)  %>
          <% @seller = User.find(@pigeon.user_id) %>
          <% if @buyer.id == current_user.id %>
            <%= render "bookings/booking_card_buyer", booking: booking, pigeon: @pigeon, seller: @seller  %>
          <% end %>
        <% end %>
    </div>
    <br>
    <br>
    <%= link_to "Back to my bookings", bookings_path, class:'btn btn-danger' %>
</div>

app/views/bookings/rent_to.html.erb
<br>
<br>
<div class="container">

  <h1>Booking Requests</h1>
  <br>

  <div class="container">
    <div>

      <div>
        <h2>Your Pending Approvals</h2>
        <div class="cards">
            <% @bookings.each do |booking| %>
            <% @pigeon = Pigeon.find(booking.pigeon_id) %>
            <% @buyer = User.find(booking.user_id) %>
            <% @seller = User.find(@pigeon.user_id) %>
              <% if @seller.id == current_user.id && booking.approved == nil %>
              <%= render "bookings/booking_card_seller", booking: booking, pigeon: @pigeon, buyer: @buyer %>
              <% end %>
            <% end %>
        </div>
      </div>

      <div>
        <h2 class="mt-5">Approved Bookings</h2>
        <div class="cards">
            <% @bookings.each do |booking| %>
            <% @pigeon = Pigeon.find(booking.pigeon_id) %>
            <% @buyer = User.find(booking.user_id) %>
            <% @seller = User.find(@pigeon.user_id) %>
              <% if @seller.id == current_user.id && booking.approved == true %>
              <%= render "bookings/booking_card_seller", booking: booking, pigeon: @pigeon, buyer: @buyer %>
              <% end %>
            <% end %>
        </div>
      </div>

      <div>
        <h2 class="mt-5">Rejected Booking</h2>
        <div class="cards">
            <% @bookings.each do |booking| %>
            <% @pigeon = Pigeon.find(booking.pigeon_id) %>
            <% @buyer = User.find(booking.user_id) %>
            <% @seller = User.find(@pigeon.user_id) %>
              <% if @seller.id == current_user.id && booking.approved == false %>
              <%= render "bookings/booking_card_seller", booking: booking, pigeon: @pigeon, buyer: @buyer %>
              <% end %>
            <% end %>
        </div>
      </div>
    </div>
    <br>
    <br>
    <%= link_to "Back to my bookings", bookings_path, class:'btn btn-flat' %>
  </div>
</div>

app/views/bookings/show.html.erb
<h1>Booking Info</h1>
<h3>Starting_date: <%= @booking.start_date %></h3>
<h3>ending_date: <%= @booking.end_date %></h3>
<h3>buyer: <%= @buyer.first_name%></h3>
<h3>pigeon: <%= @pigeon.name %></h3>
<h3>seller: <%=@seller.first_name %></h3>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>P&B</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link href="https://api.mapbox.com/mapbox-gl-js/v2.11.0/mapbox-gl.css" rel="stylesheet">
    <script src="https://api.mapbox.com/mapbox-gl-js/v2.11.0/mapbox-gl.js"></script>

    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v6.1.2/css/all.css">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>

   <%= render "shared/navbar" %>
   <%= render "shared/flashes" %>

    <%# <p class="notice"><%= notice %>
    <p class="alert"><%= alert %></p>
    <%= yield %>
    <br>
    <br>
    <%= render "shared/footer" %>
  </body>
</html>

app/views/pages/_banner.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://images.unsplash.com/photo-1632915598529-d204bae6e7c1?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1775&q=80);">
  <div class="container">
    <h1>Rent yours pigeons</strong>!</h1>
    <p> Make your monument an authentic one</p>
    <form novalidate="novalidate" class="simple_form search" action="/search" accept-charset="UTF-8" method="get">
      <div class="search-form-control form-group">
      <input class="form-control string required" type="text" name="search[query]" placeholder="Where ?" />
      <button name="button" type="submit" class="btn btn-flat">
        <i class="fas fa-search"></i> Search
      </button>
      </div>
    </form>
  </div>
</div>

app/views/pages/home.html.erb
<%= render 'banner' %>

<div class="container">
  <h2 class="d-flex justify-content-center"> Explore ours pigeons</h2>
    <%= render 'pigeons/pigeons_list', pigeons: @pigeons %>
</div>

app/views/pages/search.html.erb
<div style="margin-left:130px;">
<h4 style="margin-top:30px"><%=@count%> results for <strong style="color: brown"> "<%=params[:search][:query]%>"</strong></h4>
</div>
<div style=" display: flex;">
  <div>
    <%= render 'pigeons/pigeons_list'%>
  </div>

  <div class="sticky sticky-top { top: 0.5em; }"
      data-controller="map"
      data-map-markers-value="<%= @markers.to_json %>"
      data-map-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>">
  </div>
</div>

app/views/pigeons/_form.html.erb
<br>
<br>
<%= simple_form_for(@pigeon) do |f| %>
<%= f.input :name, placeholder:"Write the name of your pigeon"%>
<%= f.input :description %>
<%= f.input :color, collection: ['grey', 'black', 'red', 'blue'] %>
<%= f.input :photo, as: :file%>
<%= f.input :age %>
<%= f.input :price %>
<%= f.input :address %>
<%= f.submit %>
<% end %>

app/views/pigeons/_my_pigeon_card.html.erb
<a href= <%= pigeon_path(pigeon) %>>
  <div class="card-trip-pigeon m-3">
      <% if pigeon.photo.attached? %>
        <%= cl_image_tag pigeon.photo.key, height: 300, width: 400, crop: :fill %>
      <% end %>
    <div class="card-trip-infos-pigeon">

      <div>
        <h2> <%= pigeon.name %></h2>
        <p> <%= pigeon.color.capitalize %></p>
      </div>

      <div>
        <h2 class="card-trip-pricing">$<%= pigeon.price %></h2>
        <p>/per day</p>
      </div>

    </div>

    <div class="card-trip-infos-pigeon">
      <div>
        <%= link_to "Edit",
                    edit_pigeon_path(pigeon),
                    class: 'btn-flat'
                    %>

        <%= link_to "Delete",
                  pigeon_path(pigeon),
                  data: { turbo_method: :delete, turbo_confirm: 'Sure?' },
                  class: 'btn-flat'%>
      </div>
    </div>
  </div>
</a>

app/views/pigeons/_pigeon_card.html.erb
<a href= <%= pigeon_path(pigeon) %>>
  <div class="card-trip-pigeon m-3">

      <% if pigeon.photo.attached? %>
        <%= cl_image_tag pigeon.photo.key, height: 300, width:400, crop: :fill%>
      <% end %>

      <div class="card-trip-infos-pigeon">
        <div>
          <h2> <%= pigeon.name %></h2>
          <p> <%= pigeon.color.capitalize %></p>
        </div>
        <div>
          <h2 class="card-trip-pricing">$<%= pigeon.price %></h2>
          <p>/per day</p>
        </div>
          <%# <img src="https://kitt.lewagon.com/placeholder/users/krokrob" class="card-trip-user avatar-bordered" /> %>
      </div>
  </div>
</a>

app/views/pigeons/_pigeons_list.html.erb
<div class="container">
  <div class="cards d-flex justify-content-center">
      <% @pigeons.each do |pigeon| %>
        <%= render "pigeons/pigeon_card", pigeon: pigeon %>
      <% end %>
  </div>
</div>

app/views/pigeons/edit.html.erb
<br>
<br>
<div class="container">
  <h1>Edit <%= @pigeon.name %> the pigeon</h1>
<%= render 'form' %>
</div>

app/views/pigeons/index.html.erb
<h1>All the pigeons available (index)</h1>

<%= render 'pigeons/pigeons_list', pigeons: @pigeons %>

app/views/pigeons/my_pigeons.html.erb
<br>
<br>
<div class="container">

  <div class='d-flex justify-content-between align-items-start'>
    <h1>My Pigeons</h1>
    <%= link_to "+ New pigeon", new_pigeon_path, class: 'btn-ghost'%>
  </div>
  <div class="cards d-flex justify-content-center">
      <% @my_pigeons.each do |pigeon| %>
        <div>
          <%= render "pigeons/my_pigeon_card", pigeon: pigeon %>
        </div>
      <% end %>
  </div>
</div>

app/views/pigeons/new.html.erb
<br>
<br>
<div class="container">
  <h1>Add your pigeons</h1>

  <%= render 'form' %>
</div>

app/views/pigeons/show.html.erb
<div class="name">
    <h1><%= @pigeon.name %> the Pigeon</h1>
</div>

<div class="map" style="width: 100%; height: 300px;"
  data-controller="map"
  data-map-markers-value="<%= @marker.to_json %>"
  data-map-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>">
</div>

<div class="container">

  <% if @pigeon.photo.attached? %>
    <%= cl_image_tag @pigeon.photo.key, height: 180, width: 180, crop: :fill, class:'i' %>
  <% end %>

  <div class="d-flex justify-content-between">
    <div>
      <div class="box">
        <h4>Description</h4>
        <p><%= @pigeon.description %></p>
      </div>

<i class="fi fi-bs-raindrops"></i>

      <div class="box">

        <h4>Details</h4>
        <div class="boxes">
          <div class="lt-box">
            <i class="fas fa-tint fa-lg"></i>
            <p><%= @pigeon.color.capitalize %><p>
          </div>
          <div class="lt-box">
            <i class="fas fa-map-marked-alt fa-lg"></i>
            <p><%= @pigeon.address %></p>
          </div>
          <div class="lt-box">
            <i class="fas fa-dove fa-lg"></i>
            <p><%= @pigeon.age %> years old</p>
          </div>
        </div>
      </div>

      <div class="box">
        <h4>Owner</h4>
        <p><%= @owner.first_name %> <%= @owner.last_name.upcase %><p>
        <% until @owner.phone_number.nil? %>
         Phone number: <%= @owner.phone_number %>
        <% end %>

        <br>
      </div>
        <h4>Comments</h4>
        <%= simple_form_for([@pigeon, @comment]) do |f| %>
          <%= f.input :content, placeholder:"Write a review"%>
          <%= f.button :submit %>
          <% end %>
        <%= @comment.content %>

    </div>
    <div class='form sticky-top'>
      <div class="d-flex">
        <h2><strong><%= @pigeon.price %></strong></h2>
        <p>$/per day</p>
      </div>
        <p><%= render 'bookings/form' %></p>
    </div>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<body class="d-flex flex-column">
  <footer class="bg-white">
    <div class="container py-3">
      <div class="row py-4 d-flex justify-content-between">
        <div class="col-lg-4 col-md-6 mb-4 mb-lg-0">
          <h3 class="font-italic text-muted">P&B.</h3>
          <p class="font-italic text-muted">The first pigeon rental platform to make your monument <strong>authentic</strong>.</p>
          <ul class="list-inline mt-4">
            <li class="list-inline-item"><a href="#" target="_blank" title="twitter"><i class="fa-brands fa-twitter"></i></a></li>
            <li class="list-inline-item"><a href="#" target="_blank" title="facebook"><i class="fa-brands fa-facebook"></i></a></li>
            <li class="list-inline-item"><a href="#" target="_blank" title="instagram"><i class="fa-brands fa-instagram"></i></a></li>
            <li class="list-inline-item"><a href="#" target="_blank" title="pinterest"><i class="fa-brands fa-github"></i></a></li>
          </ul>
        </div>
        <div class="col-lg-4 col-md-6 mb-lg-0">
          <h6 class="text-uppercase font-weight-bold mb-4">Newsletter</h6>
          <div class="p-1 rounded border">
            <div class="input-group">
              <input type="email" placeholder="Enter your email address" aria-describedby="button-addon1" class="form-control border-0 shadow-0">
              <div class="input-group-append">
                <button id="button-addon1" type="submit" class="btn btn-link"><i class="fa fa-paper-plane"></i></button>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>

    <!-- Copyrights -->
    <div class="bg-light py-4 backgroung">
      <div class="container text-center">
        <p class="text-muted mb-0 py-2">© 2023 Le Wagon</p>
      </div>
    </div>
  </footer>
  <!-- End -->

</body>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <%= link_to "/", class: "navbar-brand" do %>
      <%= image_tag 'logo2.png', class:"w-25"%>
    <% end %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>
          <li class="nav-item active">
          </li>
          <li class="nav-item dropdown">
          <a href="#" class="avatar" id="navbarDropdown" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <%= image_tag "https://kitt.lewagon.com/placeholder/users/ssaunier", class: "avatar", alt: "dropdown menu" %>
          </a>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "New Pigeon", new_pigeon_path, class: "dropdown-item" %>
              <%= link_to "My Pigeons", my_pigeons_path, class: "dropdown-item" %>
              <%= link_to "My Bookings", bookings_path, class: "dropdown-item" %>
              <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item" %>
            </div>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          </li>
          <li>
            <%= link_to "Register", new_user_registration_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>